language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

matrix:
  include:
    - env: PIRANHA_BUILD="OSXDebug"
      os: osx
      osx_image: xcode10.2
script:
    - mkdir build
    - cd build
    # NOTE: currently, travis does not stop automatically if one of these
    # 2 scripts returns an error code. Thus, we run them together as a single
    # command, so that if install_deps.sh fails the whole build fails immediately
    # rather than executing install_travis.sh as well. See
    # https://github.com/travis-ci/travis-ci/issues/1066
    - ../tools/travis_osx.sh

notifications:
  email: false
