version: '{build}'

branches:
  except:
    - /pr\/.+/

environment:
  matrix:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    #   BUILD_TYPE: MSVC19_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILD_TYPE: MSVC17_64

install:
- set PATH=C:\Miniconda36-x64\Scripts;%PATH%
- conda config --add channels conda-forge --force
- conda create -y --name piranha cmake boost-cpp mpir mpfr ninja
- call activate piranha

build_script:
- set CONDA_PREFIX_PATH=C:\Miniconda36-x64\envs\piranha
- set CMAKE_GENERATOR=Ninja

- mkdir build
- cd build

# mp++ setup.
- set MPPP_VERSION=0.14
- curl -fsSL -o mppp.zip https://github.com/bluescarni/mppp/archive/v%MPPP_VERSION%.zip
- 7z x mppp.zip
- cd mppp-%MPPP_VERSION%
- mkdir build
- cd build
- cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Debug -DMPPP_WITH_MPFR=yes -DCMAKE_PREFIX_PATH=%CONDA_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX_PATH% -DCMAKE_CXX_STANDARD=17
- cmake --build . --target install -- -v
- cd ..
- cd ..

# abseil setup.
- git clone https://github.com/abseil/abseil-cpp.git
- cd abseil-cpp
- mkdir build
- cd build
- cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX_PATH% -DCMAKE_CXX_STANDARD=17
- cmake --build . --target install -- -v
- cd ..
- cd ..

# piranha
- cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Debug -DPIRANHA_BUILD_TESTS=yes
- cmake --build . -- -v


test_script:
# NOTE: ensure the PATH variable contains the path to the piranha dll,
# otherwise the tests will fail to run.
- set PATH=%PATH%;%CD%
- ctest -V

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
