trigger:
  - master

jobs:

  # Configure, build, install, and test job
  - job: 'build'
    pool:
      vmImage: 'vs2015-win2012r2'
    timeoutInMinutes: 360
    steps:

      # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
      - powershell: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
          choco --version
        displayName: "Install Chocolatey"

      # Install Miniconda
      - script: |
          choco install miniconda3 --yes
          set PATH=C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\tools\miniconda3\Library\bin;%PATH%
          echo '##vso[task.setvariable variable=PATH]%PATH%'
          set LIB=C:\tools\miniconda3\Library\lib;%LIB%
          echo '##vso[task.setvariable variable=LIB]%LIB%'
          conda --version
        displayName: "Install Miniconda"

      # Configure Miniconda
      - script: |
          conda config --set always_yes yes
          conda config --append channels conda-forge
          conda info
        displayName: "Configure Miniconda"

      # Create conda enviroment
      # Note: conda activate doesn't work here, because it creates a new shell!
      - script: |
          conda install cmake ^
                        clangdev ^
                        ninja ^
                        mppp ^
                        boost-cpp ^
                        python=3.6
          conda list
        displayName: "Install conda packages"

      # Install abseil.
      - script: |
          setlocal EnableDelayedExpansion
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          git clone https://github.com/abseil/abseil-cpp.git
          cd abseil-cpp
          mkdir build
          cd build
          cmake .. -G Ninja ^
                   -DCMAKE_INSTALL_PREFIX=C:\tools\miniconda3 ^
                   -DCMAKE_CXX_STANDARD=17 ^
                   -DCMAKE_BUILD_TYPE=Release ^
                   -DCMAKE_CXX_COMPILER=clang-cl
          cmake --build . --target install -- -v
          cd ..
          cd ..
        displayName: "Install abseil"

      # Configure, build and test.
      - script: |
          setlocal EnableDelayedExpansion
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          mkdir build
          cd build
          cmake .. -G Ninja ^
                -DCMAKE_BUILD_TYPE=Release ^
                -DCMAKE_C_COMPILER=clang-cl ^
                -DCMAKE_CXX_COMPILER=clang-cl ^
                -DPIRANHA_BUILD_TESTS=ON ^
                -DCMAKE_CXX_FLAGS=/std:c++17 ^
                $(Build.SourcesDirectory)
          cmake --build . -- -v
          ctest -V .
        displayName: "Configure, build and test"
