version: 2.1

jobs:
  cosmic:
    docker:
      - image: circleci/buildpack-deps:cosmic
    steps:
      - checkout
      - run:
          name: Installing deps
          command: 'sh ./tools/circleci_cosmic_install_deps.sh'

workflows:
  version: 2.1
  all_builds:
    jobs:
      - cosmic
