version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:cosmic
    steps:
      - checkout
      - run:
          name: Installing deps
          command: 'sh ./tools/circleci_install_deps.sh'
