version: 2

jobs:
  cosmic_gcc8_coverage:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_gcc8_coverage.sh
  cosmic_clang7_ubsan:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_clang7_ubsan.sh
  bionic_gcc7_asan:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_asan.sh
  bionic_clang6_tsan:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_clang6_tsan.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - cosmic_gcc8_coverage
    - cosmic_clang7_ubsan
    - bionic_gcc7_asan
    - bionic_clang6_tsan
