version: 2

jobs:
  cosmic:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: sh ./tools/circleci_cosmic.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - cosmic
